### PR TITLE
Allow node more space in packages/ui scripts

### PR DESCRIPTION
**Pull request by tevanburen**
pnpm run build was giving 
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
for some users. 

Increasing the node space seems to have fixed it.

### CODE REVIEW

**Comment by susanta96** [comment]
Hi @johbaxter , Ui folder does take lots of time to build, there are few things I am trying to improve on that. If you want, I can create a PR (need some time to test it properly).

**Comment by tevanburen** [comment]
I second that it takes much longer to build than would be ideal; it's especially noticeable on low-quality machines. The development experience would be much better if the runtime were improved

**Comment by susanta96** [comment]
Working on it. I need to test it properly .

**Comment by johbaxter** [comment]
Resolved in https://github.com/SEMOSS/semoss-ui/pull/417

**Pull request closed without merging**
