### PR TITLE
feat(client): issue with value setting for dnd variable fixed

### PR DESCRIPTION
**Pull request by soumya-pratik**
Fixed the issue where value field for variable was not populating with the saved options.

image

### CODE REVIEW

**Comment by johbaxter** [comment]
Will look at this first thing tomorrow morning @soumya-pratik

**Comment by johbaxter** [comment]
Please keep in mind other variable types.  If a refactor is needed please do so.  Also commented on this in an email.

**Comment by soumya-pratik** [comment]
> Please keep in mind other variable types. If a refactor is needed please do so. Also commented on this in an email.

Hey @johbaxter I have updated the code keeping in mind for other variable type. I have done a round of testing for all types variable, please review it.

**Comment by johbaxter** [comment]
Looks good ty @soumya-pratik

**Pull request merged**
